import org.jenkins.Defaults
import org.jenkinsci.plugins.pipeline.modeldefinition.Utils

/**
 * Main shared-library facade for Jenkins pipelines.
 *
 * The methods in this file intentionally wrap common Jenkins Pipeline idioms:
 * - consistent agent/credential defaults
 * - generated configuration file reads
 * - dynamic Active Choices parameter snippets
 * - safe shell execution through ssh-agent
 * - downstream job fan-out
 */

def defaultAgentLabel() {
    return Defaults.DEFAULT_AGENT_LABEL
}

def environments(List<String> override = null) {
    return override ?: Defaults.PSX_ENVIRONMENTS
}

def sshCredentialId(Map config = [:]) {
    return config.get('sshCredentialId', Defaults.DEFAULT_SSH_CREDENTIAL_ID)
}

def generatedConfigDir(Map config = [:]) {
    return config.get('generatedConfigDir', Defaults.GENERATED_CONFIG_DIR)
}

def deploymentScriptsDir(Map config = [:]) {
    return config.get('deploymentScriptsDir', Defaults.DEPLOYMENT_SCRIPTS_DIR)
}

def pmanDir(Map config = [:]) {
    return config.get('pmanDir', Defaults.PMAN_DIR)
}

def updateStackDir(Map config = [:]) {
    return config.get('updateStackDir', Defaults.UPDATE_STACK_DIR)
}

def ansibleDir(Map config = [:]) {
    return config.get('ansibleDir', Defaults.ANSIBLE_DIR)
}

def withSshAgent(Map config = [:], Closure body) {
    sshagent([sshCredentialId(config)]) {
        body()
    }
}

def withDeploymentScripts(Map config = [:], Closure body) {
    dir(deploymentScriptsDir(config)) {
        body()
    }
}

def withPman(Map config = [:], Closure body) {
    dir(pmanDir(config)) {
        body()
    }
}

def withUpdateStack(Map config = [:], Closure body) {
    dir(updateStackDir(config)) {
        body()
    }
}

def withAnsible(Map config = [:], Closure body) {
    dir(ansibleDir(config)) {
        body()
    }
}

def runWithSshAgent(String shellCode, Map config = [:]) {
    if (!shellCode?.trim()) {
        error('runWithSshAgent requires a non-empty shell command')
    }
    withSshAgent(config) {
        sh shellCode
    }
}

def runDeploymentScriptCommand(String shellCode, Map config = [:]) {
    withDeploymentScripts(config) {
        runWithSshAgent(shellCode, config)
    }
}

/**
 * Backwards-compatible deployment command helper for V2 Jenkinsfiles.
 * Executes a shell command from scripts/deployment inside the configured ssh-agent.
 */
def runDeploymentShell(String shellCode, Map config = [:]) {
    runDeploymentScriptCommand(shellCode, config)
}

def runScript(String scriptName, List args = [], Map config = [:]) {
    String quotedArgs = args.collect { value -> shellQuote(value as String) }.join(' ')
    String command = quotedArgs ? "./${scriptName} ${quotedArgs}" : "./${scriptName}"
    runWithSshAgent(command, config)
}

def shellQuote(String value) {
    return "'" + value.replace("'", "'\\''") + "'"
}

def selectedEnvironments(Map paramsMap, List<String> envs = Defaults.PSX_ENVIRONMENTS) {
    return envs.findAll { key ->
        def rawValue = paramsMap["env_${key}"]
        rawValue == true || rawValue == 'enable' || rawValue == 'true'
    }
}

def environmentChoiceParameter(String key, String referencedParameter = 'RELEASE', Map config = [:]) {
    String upper = key.toUpperCase()
    String configDir = generatedConfigDir(config)
    return [
        $class: 'CascadeChoiceParameter',
        choiceType: 'PT_SINGLE_SELECT',
        description: "Enable deployment for PSX ${upper}",
        name: "env_${key}",
        referencedParameters: referencedParameter,
        script: [
            $class: 'GroovyScript',
            fallbackScript: [classpath: [], sandbox: false, script: "return ['-']"],
            script: [classpath: [], sandbox: false, script: """
                def envRel = new File('${configDir}/ENV_${upper}_RELEASE').text.trim()
                if (envRel.indexOf(${referencedParameter}) != -1) {
                    return ['enable', '-']
                }
                return ['-', 'enable']
            """]
        ]
    ]
}

def environmentChoiceParameters(List<String> envs = Defaults.PSX_ENVIRONMENTS, String referencedParameter = 'RELEASE', Map config = [:]) {
    return envs.collect { key -> environmentChoiceParameter(key, referencedParameter, config) }
}

def releaseChoiceParameter(Map config = [:]) {
    String configDir = generatedConfigDir(config)
    return [
        $class: 'CascadeChoiceParameter',
        choiceType: 'PT_SINGLE_SELECT',
        description: 'Release generated by Jenkins configuration builder',
        name: 'RELEASE',
        script: [
            $class: 'GroovyScript',
            fallbackScript: [classpath: [], sandbox: false, script: 'return []'],
            script: [classpath: [], sandbox: false, script: """
                def result = []
                new File('${configDir}/RELEASE').eachLine { line -> result.add(line) }
                return result
            """]
        ]
    ]
}

def rebuildSettings() {
    return [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false]
}

def applyParameters(List parameterDefinitions) {
    properties([parameters(parameterDefinitions), rebuildSettings()])
}

def buildBooleanParam(String name, Object value) {
    return booleanParam(name: name, value: asBoolean(value))
}

def buildStringParam(String name, Object value) {
    return string(name: name, value: value == null ? '' : value.toString())
}

def buildJobParameter(String name, Object value) {
    if (!name?.trim()) {
        error('Downstream build parameter name must not be empty')
    }

    if (value instanceof Boolean || value in ['true', 'false', 'enable', '-']) {
        return buildBooleanParam(name, value)
    }

    return buildStringParam(name, value)
}

def triggerJob(String jobName, Map paramsMap = [:], Map options = [:]) {
    if (!jobName?.trim()) {
        error('triggerJob requires a non-empty job name')
    }

    List downstreamParams = paramsMap.collect { key, value ->
        buildJobParameter(key as String, value)
    }

    Map buildArgs = [
        job: jobName,
        propagate: asBoolean(options.get('propagate', true)),
        wait: asBoolean(options.get('wait', true))
    ]

    if (!downstreamParams.isEmpty()) {
        buildArgs.parameters = downstreamParams
    }
    if (options.containsKey('quietPeriod')) {
        buildArgs.quietPeriod = options.quietPeriod as Integer
    }

    return build(buildArgs)
}

def asBoolean(Object value) {
    return value == true || value?.toString()?.equalsIgnoreCase('true') || value == 'enable'
}

def conditionalStage(String name, Object execute, Closure block) {
    return stage(name, asBoolean(execute) ? block : {
        echo 'Stage "' + name + '" skipped due to when conditional.'
        Utils.markStageSkippedForConditional(STAGE_NAME)
    })
}

def readConfigFile(String configPath = Defaults.CONFIG_FILE) {
    return sh(script: "cat ${shellQuote(configPath)}", returnStdout: true)
}

def parsedConfig(String configPath = Defaults.CONFIG_FILE) {
    return new ConfigSlurper().parse(new File(configPath).toURI().toURL())
}

def isEnvironmentActive(String environment, String configPath = Defaults.CONFIG_FILE) {
    def deactivated = parsedConfig(configPath).envs_deactivated ?: []
    return !deactivated.contains(environment)
}

def dataTypeName(String dataType) {
    switch (dataType) {
        case 'EKTR_19':
        case 'EKTR_29':
            return 'VL_NPS_EBPB'
        case 'nvs_abo_verbund':
        case 'tpo_verbund':
            return 'nvs-abo-verbund'
        case 'LTBW_ABO':
            return 'LTBW-ABO'
        case 'connection_review':
            return 'connection-review'
        case 'connection_preview':
            return 'connection-preview'
        default:
            return dataType
    }
}

def unstableStage(Closure body) {
    catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
        body()
    }
}
