#!/bin/bash
#
# uname -r auf allen Instanzen
#

LISTE="$(ec2admin list -r)"

for ARG
do
  LISTE=$( echo "$LISTE" | grep -i $ARG )
  # echo "### $ARG ###"
  # echo "$LISTE"
done

IPLISTE=$( echo "$LISTE" | cut -c20-35 )

for IP in $IPLISTE
do
  if ssh $IP yum list qualys-cloud-agent >/dev/null 2>&1
  then echo -n "$IP     qualys OK       "
  else echo -n "$IP     qualys NOK      "
  fi
  echo "$LISTE" | grep "$IP " | tr -s " " | cut -d " " -f8
done

exit

# i-06e740e6caaf76a52 10.105.36.59 running no no 2018-08-31 14:31:35 nvs-psxk-appsrv-tt-1
