# vim:ft=ansible:

---

# ===========================================================================
#  multiple listeners for "restart hafas"

- name: hafas.sh restart
  shell: "nohup {{ app_home }}/bin/hafas.sh restart"
  listen: "restart hafas"
  ignore_errors: true
  when: ( skip_restart_handler | bool == False ) and ( bootstrap | bool == False )

- name: sendlog test
  shell: "{{ app_home }}/bin/sendlog/testcase.sh"
  listen: "restart hafas"
  when: ( skip_restart_handler | bool == False ) and ( bootstrap | bool == False )

# ===========================================================================
